name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        # Fetch all tags/history
        fetch-depth: 0
    - name: Calculate version
      id: calculate-minver-version
      run: >
        dotnet tool install --global minver-cli --version 3.1.0;
        VERSION=$(minver . --verbosity warn);
        if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9a-zA-Z.]*)?(\+[0-9a-zA-Z]*)?$ ]]; then
          echo "::info Found version: $VERSION";
          echo "::set-output name=MINVER_VERSION::$VERSION";
        else
          echo "::error Invalid version: $VERSION";
          exit 1;
        fi

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Build Docker image
      run: >
        cd dbot;
        docker buildx create --use;
        docker buildx build --platform linux/amd64,linux/arm/v7 --tag dktrotti/moviebot:${{ steps.calculate-minver-version.outputs.MINVER_VERSION }} .;
